// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDEr1tND-bbAorSY-6qpVmudh1LKgeMxA',
    appId: '1:128696037827:web:42aebdec79b3aa00fb4d76',
    messagingSenderId: '128696037827',
    projectId: 'medy24-new',
    authDomain: 'medy24-new.firebaseapp.com',
    storageBucket: 'medy24-new.firebasestorage.app',
    measurementId: 'G-RX2RSXWV9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOgbQZZ7Lbt58Gstg4YnvBUcw3tRtKiIk',
    appId: '1:128696037827:android:4494d40549950074fb4d76',
    messagingSenderId: '128696037827',
    projectId: 'medy24-new',
    storageBucket: 'medy24-new.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEJSsTu9HqDLwzd76VUDuPaX5Mpony528',
    appId: '1:128696037827:ios:a5e14d7089b83f3efb4d76',
    messagingSenderId: '128696037827',
    projectId: 'medy24-new',
    storageBucket: 'medy24-new.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEJSsTu9HqDLwzd76VUDuPaX5Mpony528',
    appId: '1:128696037827:ios:a5e14d7089b83f3efb4d76',
    messagingSenderId: '128696037827',
    projectId: 'medy24-new',
    storageBucket: 'medy24-new.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDEr1tND-bbAorSY-6qpVmudh1LKgeMxA',
    appId: '1:128696037827:web:012a6d64f559e22ffb4d76',
    messagingSenderId: '128696037827',
    projectId: 'medy24-new',
    authDomain: 'medy24-new.firebaseapp.com',
    storageBucket: 'medy24-new.firebasestorage.app',
    measurementId: 'G-Y6LBW6CD5D',
  );
}
